### ISSUE TITLE
游戏门槛

### ISSUE THREAD

**Issue by lhfly5201314** [evolutionlandorg/land#17]
感觉现在EvolutionLand的参与门槛还是太高了。特别是MetaMask这一关。即使币圈的币民很多都会被卡主，更不用说小白玩家了。
我觉得一定要想办法打开法币进入游戏的通道，解决MetaMask+翻墙的问题，要不然太难带来流量了！

**Comment by HackFisher** [comment]
We are trying to improve this by cooperating with Itering ID app, Thanks for your suggestion.

Here is the website of Itering ID: https://id.itering.com
