### ISSUE TITLE
Support approveAndCall features for ERC721 contract.

### ISSUE THREAD

**Issue by HackFisher** [evolutionlandorg/land#5]
https://github.com/ConsenSys/Token-Factory/blob/master/contracts/HumanStandardToken.sol#L58

https://github.com/evolutionlandorg/token-contracts/blob/master/src/RING.sol#L130

https://github.com/evolutionlandorg/token-contracts/blob/master/src/ApproveAndCallFallBack.sol

There could similar features in ERC721 just like ERC20.

**Comment by hammeWang** [comment]
solved. details at:
https://github.com/evolutionlandorg/land/commit/bb1d5e1ee71d5932a532c31ce225a2df06ce40c1

**Comment by HackFisher** [comment]
added to ObjectOwnership, and auth is done in parent contract.
